import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, cast

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CustomBuildHook(BuildHookInterface[Any]):
    """Dump pyproject metadata to a _config.py app can easily injest, and
    compile GTK blueprints into .ui files that get packed with other
    resources into a .gresource"""

    PLUGIN_NAME = "jankhook"

    def initialize(self, version: str, build_data: dict[str, Any]):
        # write pkg metadata to _config.py
        CFG = self.metadata.config  # type: ignore
        APP_ID = cast("str", CFG["tool"]["gtk"]["app-id"])  # type: ignore
        APP_PATH = "/" + APP_ID.replace(".", "/")
        APP_NAME = cast("str", CFG["project"]["name"])
        RESOURCE_DIR = Path("resources")
        OUTPUT_DIR = Path(f"src/{APP_NAME}")

        target = OUTPUT_DIR / "_config.py"
        print(f"Compiling package metadata into: {target}")
        with target.open("w") as file:
            file.write(f"# Autogenerated by {self.PLUGIN_NAME}\n")
            file.write(f'APP_NAME = "{CFG["project"]["name"]}"\n')
            file.write(f'APP_ID = "{APP_ID}"\n')
            file.write(f'APP_PATH = "{APP_PATH}"\n')
            file.write(f'APP_TITLE = "{CFG["tool"]["gtk"]["app-title"]}"\n')
            file.write(f'DESCRIPTION = "{CFG["project"]["description"]}"\n')
            file.write(f'AUTHOR = "{CFG["project"]["authors"][0]["name"]}"\n')
            file.write(f'HOMEPAGE = "{CFG["project"]["urls"]["Homepage"]}"\n')
            file.write(f'REPOSITORY = "{CFG["project"]["urls"]["Repository"]}"\n')
            file.write(f'BUG_TRACKER = "{CFG["project"]["urls"]["Bug Tracker"]}"\n')
            file.write(f'GTK_LICENSE = "{CFG["tool"]["gtk"]["license"]}"\n')
            file.write("\n")

        # compile blueprints
        compiled_ui_files: list[Path] = []
        for blp_path in RESOURCE_DIR.rglob("*.blp"):
            relative_path = blp_path.relative_to(RESOURCE_DIR)
            ui_path = RESOURCE_DIR / relative_path.with_suffix(".ui")

            print(f"Compiling blueprint: {blp_path} -> {ui_path}")
            subprocess.run(
                [
                    "blueprint-compiler",
                    "compile",
                    "--output",
                    str(ui_path),
                    str(blp_path),
                ],
                check=True,
            )
            compiled_ui_files.append(ui_path)

        # compile settings schema
        subprocess.run(["glib-compile-schemas", str(RESOURCE_DIR)], check=True)
        (RESOURCE_DIR / "gschemas.compiled").copy_into(OUTPUT_DIR)

        # generate gresource.xml
        root = ET.Element("gresources")
        gresource_el = ET.SubElement(root, "gresource", prefix=APP_PATH)

        resources = [
            *RESOURCE_DIR.rglob("*.ui"),
            *RESOURCE_DIR.rglob("*.css"),
            *RESOURCE_DIR.rglob("*.svg"),
            *RESOURCE_DIR.rglob("*.ttf"),
        ]

        SKIP_XML_PREPROCESS = [".css", ".ttf"]
        for file_path in resources:
            relative_path = file_path.relative_to(RESOURCE_DIR)
            attrib = (
                {"preprocess": "xml-stripblanks"}
                if file_path.suffix not in SKIP_XML_PREPROCESS
                else {}
            )
            file_el = ET.SubElement(gresource_el, "file", attrib=attrib)
            file_el.text = str(relative_path)

        tree = ET.ElementTree(root)
        ET.indent(tree, space="  ")
        tree.write(
            RESOURCE_DIR / "gresource.xml", encoding="utf-8", xml_declaration=True
        )

        # build resource file
        output_resource_file = OUTPUT_DIR / f"{APP_NAME}.gresource"
        print(f"Compiling resources into: {output_resource_file}")
        subprocess.run(
            [
                "glib-compile-resources",
                f"--sourcedir={RESOURCE_DIR}",
                f"--target={output_resource_file}",
                str(RESOURCE_DIR / "gresource.xml"),
            ],
            check=True,
        )

        # trash temporary files
        (RESOURCE_DIR / "gresource.xml").unlink(missing_ok=True)
        (RESOURCE_DIR / "gschemas.compiled").unlink(missing_ok=True)
        for ui_file in compiled_ui_files:
            ui_file.unlink(missing_ok=True)
