[project]
dynamic = ["version"]
name = "jankportal"
description = "yafti-gtk, re-imagined by a madman"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.14"
authors = [
    { name = "h3lmut" }
]
dependencies = [
    "evdev>=1.9.3",
    "markdown>=3.10.3",
    #"pyudev>=0.24.4",
    "pyyaml>=6.0.3",
    "requests>=2.33.1",
]

[project.urls]
Homepage = "https://github.com/gminteer/jankportal/#README"
Repository = "https://github.com/gminteer/jankportal.git"
"Bug Tracker" = "https://github.com/gminteer/jankportal/issues"

[dependency-groups]
dev = [
    "hatchling>=1.32.4",
    "pygobject-stubs>=2.17.0",
    "uv-dynamic-versioning>=0.14.1",
]

[project.scripts]
jankportal = "jankportal.app:main"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.gtk]
app-id = "io.github.gminteer.jankportal"
app-title = "Jank Portal"
license = "GPL_3_0"

[tool.rpm]
description = "This is a clone of Bazzite Portal with some additional features"

[tool.pyright]
reportMissingModuleSource = false
reportUnusedImport = false
reportUnusedVariable = false
typeCheckingMode = "strict"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
extend-select = [
    "F",        # Pyflakes rules
    "W",        # PyCodeStyle warnings
    "E",        # PyCodeStyle errors
    "I",        # Sort imports properly
    "UP",       # Warn if certain things can changed due to newer Python versions
    "C4",       # Catch incorrect use of comprehensions, dict, list, etc
    "FA",       # Enforce from __future__ import annotations
    "ISC",      # Good use of string concatenation
    "ICN",      # Use common import conventions
    "RET",      # Good return practices
    "SIM",      # Common simplification rules
    "TID",      # Some good import practices
    "TC",       # Enforce importing certain types in a TYPE_CHECKING block
    "PTH",      # Use pathlib instead of os.path
    "TD",       # Be diligent with TODO comments
    "NPY",      # Some numpy-specific things
    "FURB",     # Suggest more idiomatic Python patterns
]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
line-ending = "auto"
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[tool.hatch.build.targets.wheel]
artifacts = [
    "src/jankportal/*.gresource",
    "src/jankportal/_config.py",
    "src/jankportal/gschemas.compiled",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
fallback-version = "0.1.0"
vcs = "git"
style = "pep440"
metadata = true
dirty = true

[external]
# the scripts blindly assume "dep:pkg:rpm/fedora/$package@>=$version"
# (don't violate this constraint without dealing with it)
build-requires = [
    "dep:pkg:rpm/fedora/blueprint-compiler@>=0.20.4",
    "dep:pkg:rpm/fedora/glib2-devel@>=2.88.3",
]
host-requires = [
    "dep:pkg:rpm/fedora/python3-gobject@>=3.56.3",
    "dep:pkg:rpm/fedora/libadwaita@>=1.9.4",
    "dep:pkg:rpm/fedora/vte-2.91-gtk4@>=0.84.1",
    "dep:pkg:rpm/fedora/webkitgtk6.0@>=2.54.0",
]
