[project]
name = "jankportal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "blueprint-compiler>=0.22.2",
    "pygobject-stubs>=2.17.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
app = "app:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pyright]
reportMissingModuleSource = false
typeCheckingMode = "strict"

[tool.setuptools.packages.find]
where = ["src"]
